flowchart TD
  ENTER_NW_API(Enter the TCP/IP stack via a cross-compartment call)

  ENTER_NW_API --> ENTER_NW_SOCKET_CLOSE
  ENTER_NW_SOCKET_CLOSE(Enter `network_socket_close`) --> NW_SOCKET_CLOSE_WAIT_SOCKET_LOCK
  ENTER_NW_SOCKET_CLOSE:::CompEntryPoint

  ENTER_NW_API --> ENTER_NW_SOCKET_SEND_TO
  ENTER_NW_SOCKET_SEND_TO(Enter `network_socket_send_to`) --> NW_SOCKET_SEND_TO_WAIT_SOCKET_LOCK
  ENTER_NW_SOCKET_SEND_TO:::CompEntryPoint

  ENTER_NW_API --> ENTER_NW_SOCKET_SEND
  ENTER_NW_SOCKET_SEND(Enter `network_socket_send`) --> NW_SOCKET_SEND_WAIT_SOCKET_LOCK
  ENTER_NW_SOCKET_SEND:::CompEntryPoint

  ENTER_NW_API --> ENTER_NW_SOCKET_RECEIVE_FROM
  ENTER_NW_SOCKET_RECEIVE_FROM(Enter `network_socket_receive_from`) --> NW_SOCKET_RECEIVE_FROM_WAIT_SOCKET_LOCK
  ENTER_NW_SOCKET_RECEIVE_FROM:::CompEntryPoint

  ENTER_NW_API --> ENTER_NW_SOCKET_RECEIVE
  ENTER_NW_SOCKET_RECEIVE(Enter `network_socket_receive`) --> CALL_NW_SOCKET_RECEIVE_INTERNAL
  ENTER_NW_SOCKET_RECEIVE:::CompEntryPoint

  ENTER_NW_API --> ENTER_NW_SOCKET_RECEIVE_PREALLOCATED
  ENTER_NW_SOCKET_RECEIVE_PREALLOCATED(Enter `network_socket_receive_preallocated`) --> CALL_NW_SOCKET_RECEIVE_INTERNAL
  ENTER_NW_SOCKET_RECEIVE_PREALLOCATED:::CompEntryPoint

  CALL_NW_SOCKET_RECEIVE_INTERNAL(Call `network_socket_receive_internal`) --> NW_SOCKET_RECEIVE_INTERNAL_WAIT_SOCKET_LOCK

  subgraph Socket lock mutex area
  NW_SOCKET_CLOSE_WAIT_SOCKET_LOCK(Wait for socket lock)
  NW_SOCKET_CLOSE_WAIT_SOCKET_LOCK:::WaitState

  NW_SOCKET_SEND_TO_WAIT_SOCKET_LOCK(Wait for socket lock)
  NW_SOCKET_SEND_TO_WAIT_SOCKET_LOCK:::WaitState

  NW_SOCKET_SEND_WAIT_SOCKET_LOCK(Wait for socket lock)
  NW_SOCKET_SEND_WAIT_SOCKET_LOCK:::WaitState

  NW_SOCKET_RECEIVE_FROM_WAIT_SOCKET_LOCK(Wait for socket lock)
  NW_SOCKET_RECEIVE_FROM_WAIT_SOCKET_LOCK:::WaitState

  NW_SOCKET_RECEIVE_INTERNAL_WAIT_SOCKET_LOCK(Wait for socket lock)
  NW_SOCKET_RECEIVE_INTERNAL_WAIT_SOCKET_LOCK:::WaitState
  end

  NW_SOCKET_SEND_WAIT_SOCKET_LOCK --> CALL_FREERTOS_SEND

  NW_SOCKET_CLOSE_WAIT_SOCKET_LOCK --> CALL_FREERTOS_SHUTDOWN
  NW_SOCKET_SEND_TO_WAIT_SOCKET_LOCK --> CALL_FREERTOS_SENDTO
  NW_SOCKET_RECEIVE_FROM_WAIT_SOCKET_LOCK --> CALL_FREERTOS_RECV_FROM
  NW_SOCKET_RECEIVE_INTERNAL_WAIT_SOCKET_LOCK --> CALL_FREERTOS_RECV

  CALL_FREERTOS_SHUTDOWN(Call `FreeRTOS_shutdown`) --> FREERTOS_SHUTDOWN_WAIT_MESSAGE_QUEUE_LOCK
  CALL_FREERTOS_SHUTDOWN:::FreeRTOSCall

  CALL_FREERTOS_CLOSESOCKET(Call `FreeRTOS_closesocket`) --> FREERTOS_MESSAGE_QUEUE_LOCK
  CALL_FREERTOS_CLOSESOCKET:::FreeRTOSCall

  CALL_FREERTOS_SENDTO(Call `FreeRTOS_sendto`) --> FREERTOS_MESSAGE_QUEUE_LOCK
  CALL_FREERTOS_SENDTO:::FreeRTOSCall

  CALL_FREERTOS_RECV_FROM(Call `FreeRTOS_recvfrom`) --> FREERTOS_RECV_FROM_WAIT_EVENT_GROUP_LOCK
  CALL_FREERTOS_RECV_FROM:::FreeRTOSCall

  CALL_FREERTOS_RECV(Call `FreeRTOS_recv`) --> FREERTOS_WAIT_EVENT_GROUP_LOCK
  CALL_FREERTOS_RECV:::FreeRTOSCall

  CALL_FREERTOS_SEND(Call `FreeRTOS_send`) --> FREERTOS_SEND_WAIT_SUSPEND_FLAG_LOCK
  CALL_FREERTOS_SEND:::FreeRTOSCall

  subgraph "Socket event group wait area (IP Thread -> User Threads communication)"
  FREERTOS_IP_THREAD_WAIT_EVENT_GROUP_LOCK(Wait on event group lock)
  FREERTOS_IP_THREAD_WAIT_EVENT_GROUP_LOCK:::WaitState

  FREERTOS_RECV_FROM_WAIT_EVENT_GROUP_LOCK(Wait on event group lock) --> FREERTOS_RECV_FROM_WAIT_EVENT_GROUP_FUTEX
  FREERTOS_RECV_FROM_WAIT_EVENT_GROUP_LOCK:::WaitState

  FREERTOS_RECV_FROM_WAIT_EVENT_GROUP_FUTEX(Wait on event group futex)
  FREERTOS_RECV_FROM_WAIT_EVENT_GROUP_FUTEX:::WaitState

  FREERTOS_WAIT_EVENT_GROUP_LOCK(Wait on event group lock) --> FREERTOS_WAIT_EVENT_GROUP_FUTEX
  FREERTOS_WAIT_EVENT_GROUP_LOCK:::WaitState

  FREERTOS_WAIT_EVENT_GROUP_FUTEX(Wait on event group futex)
  FREERTOS_WAIT_EVENT_GROUP_FUTEX:::WaitState
  end

  FREERTOS_RECV_FROM_WAIT_EVENT_GROUP_FUTEX --> FREERTOS_RECV_FROM_WAIT_CRITICAL_SECTION_LOCK

  subgraph Network stack critical section  `SuspendFlagLock`
  FREERTOS_SEND_WAIT_SUSPEND_FLAG_LOCK(Wait on `SuspendFlagLock`)
  FREERTOS_SEND_WAIT_SUSPEND_FLAG_LOCK:::WaitState

  FREERTOS_IP_EVENT_LOOP_SUSPEND_FLAG_LOCK(Wait on `SuspendFlagLock`)
  FREERTOS_IP_EVENT_LOOP_SUSPEND_FLAG_LOCK:::WaitState
  end

  FREERTOS_SEND_WAIT_SUSPEND_FLAG_LOCK --> FREERTOS_WAIT_EVENT_GROUP_LOCK

  subgraph Network stack critical section `CriticalSectionFlagLock`
  FREERTOS_RECV_FROM_WAIT_CRITICAL_SECTION_LOCK(Wait on `CriticalSectionFlagLock`)
  FREERTOS_RECV_FROM_WAIT_CRITICAL_SECTION_LOCK:::WaitState

  FREERTOS_IP_EVENT_LOOP_WAIT_CRITICAL_SECTION_LOCK(Wait on `CriticalSectionFlagLock`)
  FREERTOS_IP_EVENT_LOOP_WAIT_CRITICAL_SECTION_LOCK:::WaitState
  end

  subgraph "Network stack message queue lock (User Threads -> IP Thread communication)"
  FREERTOS_SHUTDOWN_WAIT_MESSAGE_QUEUE_LOCK(Wait on message queue lock) --> CALL_FREERTOS_CLOSESOCKET
  FREERTOS_SHUTDOWN_WAIT_MESSAGE_QUEUE_LOCK:::WaitState

  FREERTOS_MESSAGE_QUEUE_LOCK(Wait on message queue lock)
  FREERTOS_MESSAGE_QUEUE_LOCK:::WaitState

  FREERTOS_BIND_WAIT_MESSAGE_QUEUE_LOCK(Wait on message queue lock)
  FREERTOS_BIND_WAIT_MESSAGE_QUEUE_LOCK:::WaitState

  FREERTOS_IP_THREAD_WAIT_MESSAGE_QUEUE_LOCK(Wait on message queue lock)
  FREERTOS_IP_THREAD_WAIT_MESSAGE_QUEUE_LOCK:::WaitState
  end

  FREERTOS_WAIT_EVENT_GROUP_FUTEX --> LEAVE_NW_API
  FREERTOS_RECV_FROM_WAIT_CRITICAL_SECTION_LOCK --> LEAVE_NW_API
  FREERTOS_BIND_WAIT_MESSAGE_QUEUE_LOCK --> FREERTOS_WAIT_EVENT_GROUP_LOCK
  FREERTOS_MESSAGE_QUEUE_LOCK --> LEAVE_NW_API

  ENTER_NW_API --> ENTER_NW_SOCKET_KIND
  ENTER_NW_SOCKET_KIND(Enter `network_socket_kind`) --> LEAVE_NW_API
  ENTER_NW_SOCKET_KIND:::CompEntryPoint

  ENTER_NW_API --> ENTER_NW_SOCKET_UDP
  ENTER_NW_SOCKET_UDP(Enter `network_socket_udp`) --> ENTER_NW_SOCKET_KIND
  ENTER_NW_SOCKET_UDP:::CompEntryPoint

  ENTER_NW_API --> ENTER_NW_HOST_RESOLVE
  ENTER_NW_HOST_RESOLVE(Enter `network_host_resolve`) --> CALL_FREERTOS_GETADDRINFO
  ENTER_NW_HOST_RESOLVE:::CompEntryPoint
  CALL_FREERTOS_GETADDRINFO(Call `FreeRTOS_getaddrinfo`) --> LEAVE_NW_API
  CALL_FREERTOS_GETADDRINFO:::FreeRTOSCall

  ENTER_NW_API --> ENTER_NW_CREATE_SOCKET_AND_BIND
  ENTER_NW_CREATE_SOCKET_AND_BIND(Enter `network_create_socket_and_bind`) --> CALL_FREERTOS_SOCKET
  ENTER_NW_CREATE_SOCKET_AND_BIND:::CompEntryPoint
  CALL_FREERTOS_SOCKET(Call `FreeRTOS_Socket`) --> CALL_FREERTOS_BIND
  CALL_FREERTOS_SOCKET:::FreeRTOSCall
  CALL_FREERTOS_BIND(Call `FreeRTOS_Bind`) --> FREERTOS_BIND_WAIT_MESSAGE_QUEUE_LOCK
  CALL_FREERTOS_BIND:::FreeRTOSCall

  ENTER_NW_API --> ENTER_NW_START
  ENTER_NW_START(Enter `network_start`) -->|Initialize the network stack| NW_START_INIT_WAIT
  ENTER_NW_START:::CompEntryPoint
  NW_START_INIT_WAIT(Wait for `state` to reach `Done`) --> LEAVE_NW_API
  NW_START_INIT_WAIT:::WaitState

  LEAVE_NW_API(Exit the TCP/IP stack)

  ENTER_IP_THREAD_ENTRY_POINT("Enter `ip_thread_entry` (started by the loader)")
  ENTER_IP_THREAD_ENTRY_POINT:::CompEntryPoint
  ENTER_IP_THREAD_ENTRY_POINT --> WAIT_IP_THREAD_ENTRY_GUARD
  WAIT_IP_THREAD_ENTRY_GUARD(Wait for IP thread entry guard) --> IP_EVENT_LOOP
  WAIT_IP_THREAD_ENTRY_GUARD:::WaitState

  IP_EVENT_LOOP(IP Thread event loop)
  IP_EVENT_LOOP <--> FREERTOS_IP_THREAD_WAIT_MESSAGE_QUEUE_LOCK
  IP_EVENT_LOOP <--> FREERTOS_IP_THREAD_WAIT_EVENT_GROUP_LOCK
  IP_EVENT_LOOP <--> FREERTOS_IP_EVENT_LOOP_SUSPEND_FLAG_LOCK
  IP_EVENT_LOOP <--> FREERTOS_IP_EVENT_LOOP_WAIT_CRITICAL_SECTION_LOCK
  FREERTOS_IP_EVENT_LOOP_WAIT_CRITICAL_SECTION_LOCK <--> FREERTOS_IP_EVENT_LOOP_SUSPEND_FLAG_LOCK

  classDef WaitState fill: #db6d85
  classDef CompEntryPoint fill: #6eb756
