compartment("DNS")
  add_deps("unwind_error_handler")
  add_includedirs("../../include")
  on_load(function(target)
    target:add('options', "IPv6")
    local IPv6 = get_config("IPv6")
    target:add("defines", "CHERIOT_RTOS_OPTION_IPv6=" .. tostring(IPv6))
  end)
  add_files("dns.cc")

