name: CHERIoT Network-Stack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      devcontainer:
        description: 'Set to override default build container'
        type: string
        required: false

jobs:
  check-format:
    name: Check coding conventions
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cheriot-platform/devcontainer:latest
      options: --user 1001
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Check out RTOS
      run: |
        cd ..
        git clone --recurse https://github.com/Microsoft/cheriot-rtos
    - name: Run clang-format and clang-tidy
      run: ./scripts/run_clang_tidy_format.sh /cheriot-tools/bin
  build-examples:
      strategy:
        matrix:
          build-type: [ debug, release ]
          board: [ibex-arty-a7-100, sonata-0.2, sonata-1.1]
          include:
            - xmake-run: false
            - build-type: debug
              build-flags: --debug-loader=y --debug-scheduler=y --debug-allocator=information --allocator-rendering=y -m debug
            - build-type: release
              build-flags: --debug-loader=n --debug-scheduler=n --debug-allocator=none -m release --stack-usage-check-allocator=y --stack-usage-check-scheduler=y
        fail-fast: false
      runs-on: ubuntu-latest
      container:
        image: ${{ inputs.devcontainer || 'ghcr.io/cheriot-platform/devcontainer:latest' }}
        options: --user 1001
      steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Check out RTOS
        run: |
          cd ..
          git clone --recurse https://github.com/Microsoft/cheriot-rtos
      - name: Build Examples
        run: |
          for d in examples/*/; do (
            cd $d
            xmake f --sdk=/cheriot-tools/ --board=${{matrix.board}} ${{ matrix.build-flags }}
            xmake
          ); done
  all-checks:
    needs: [check-format,build-examples]
    runs-on: ubuntu-latest
    steps:
    - name: Dummy step
      run: true
