name: CHERIoT RTOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-format:
    name: Check coding conventions
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cheriot-platform/devcontainer:latest
      options: --user 1001
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Check out RTOS
      run: |
        cd ..
        git clone --recurse https://github.com/Microsoft/cheriot-rtos
    - name: Run clang-format and clang-tidy
      run: ./scripts/run_clang_tidy_format.sh /cheriot-tools/bin

  all-checks:
    needs: [check-format]
    runs-on: ubuntu-latest
    steps:
    - name: Dummy step
      run: true
